# Generated by Django 2.1.7 on 2019-03-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('location', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250, null=True)),
                ('established_year', models.DateField()),
                ('rating', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
