# Generated by Django 2.1.7 on 2019-03-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('kind', models.CharField(max_length=250)),
                ('year_of_creation', models.DateTimeField()),
                ('milleage', models.IntegerField(default=0, null=True)),
                ('color', models.CharField(max_length=250, null=True)),
                ('car_maker', models.CharField(max_length=250, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('car_engine_no', models.CharField(max_length=250, null=True, unique=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('status', models.CharField(default='new', max_length=250)),
                ('price', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
