# Generated by Django 2.1.7 on 2019-03-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_maker',
        ),
    ]
